version: '3'
services:

    minio0:
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        ports:
            - 9000:9000
        volumes:
            - ./minio0-volume:/export0
            - ./minio6-volume:/export1
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION: us-east-1
        command:
            - server
            - http://minio0/export0
            - http://minio0/export1
            - http://minio1/export0
            - http://minio1/export1
            - http://minio2/export0
            - http://minio2/export1
            - http://minio3/export0
            - http://minio3/export1
            - http://minio4/export0
            - http://minio4/export1
            - http://minio5/export0
            - http://minio5/export1

    minio1:
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        ports:
            - 9001:9000
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION: us-east-1
        command:
            - server
            - http://minio0/export0
            - http://minio0/export1
            - http://minio1/export0
            - http://minio1/export1
            - http://minio2/export0
            - http://minio2/export1
            - http://minio3/export0
            - http://minio3/export1
            - http://minio4/export0
            - http://minio4/export1
            - http://minio5/export0
            - http://minio5/export1

    minio2:
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        volumes:
            - ./minio2-volume:/export0
            - ./minio8-volume:/export1
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION: us-east-1
        command:
            - server
            - http://minio0/export0
            - http://minio0/export1
            - http://minio1/export0
            - http://minio1/export1
            - http://minio2/export0
            - http://minio2/export1
            - http://minio3/export0
            - http://minio3/export1
            - http://minio4/export0
            - http://minio4/export1
            - http://minio5/export0
            - http://minio5/export1

    minio3:
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION: us-east-1
        command:
            - server
            - http://minio0/export0
            - http://minio0/export1
            - http://minio1/export0
            - http://minio1/export1
            - http://minio2/export0
            - http://minio2/export1
            - http://minio3/export0
            - http://minio3/export1
            - http://minio4/export0
            - http://minio4/export1
            - http://minio5/export0
            - http://minio5/export1

    minio4:
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        volumes:
            - ./minio4-volume:/export0
            - ./minio10-volume:/export1
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION: us-east-1
        command:
            - server
            - http://minio0/export0
            - http://minio0/export1
            - http://minio1/export0
            - http://minio1/export1
            - http://minio2/export0
            - http://minio2/export1
            - http://minio3/export0
            - http://minio3/export1
            - http://minio4/export0
            - http://minio4/export1
            - http://minio5/export0
            - http://minio5/export1

    minio5:
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION: us-east-1
        command:
            - server
            - http://minio0/export0
            - http://minio0/export1
            - http://minio1/export0
            - http://minio1/export1
            - http://minio2/export0
            - http://minio2/export1
            - http://minio3/export0
            - http://minio3/export1
            - http://minio4/export0
            - http://minio4/export1
            - http://minio5/export0
            - http://minio5/export1
