FROM mesosphere/mesos-slave:1.3.0

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb /

COPY ./entrypoint.slave.sh /entrypoint.dind.sh

RUN dpkg -i /dumb-init_*.deb && chmod +x /entrypoint.dind.sh
ENTRYPOINT ["/entrypoint.dind.sh"]
