version: '2'
services:
    
    minio:
        image: minio/minio:latest
        restart: always
        ports:
            - 9000:9000
        command: [ "server", "/export" ]
        environment:
            MINIO_ACCESS_KEY: minioaccesskey
            MINIO_SECRET_KEY: miniosecretkey
            MINIO_REGION: us-east-1

    registry:
        image: registry:2.6
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./registry-config.yml:/etc/docker/registry/config.yml
        links:
            - minio
